### ISSUE TITLE
Embedding a fragment into a query?

### ISSUE THREAD

**Issue by adamw** [AugustNagro/magnum#34] opened 2024-08-06 11:33 UTC
In my first attempts to constructing dynamic queries, I had something like:

```scala
def findFiltered(filter: Frag) = sql"SELECT * FROM table WHERE $filter"

findFiltered(sql"age = 12")
```

However, it turns out that you can't embed `Frag`s into interpolated `sql` queries. Is this by design?

I've since discovered `Spec`, which for now meets my needs, but I suspect that once dynamic queries with `JOIN`s or such come into play, `Spec` might no longer be enough.

**Comment by AugustNagro** [comment] 2024-08-07 04:19
> However, it turns out that you can't embed Frags into interpolated sql
queries. Is this by design?

It's definitely something we can implement, but hopefully the Spec
abstraction will cover your dynamic query use case.

> I've since discovered Spec, which for now meets my needs, but I suspect
that once dynamic queries with JOINs or such come into play, Spec might no
longer be enough.

When joins are required, create a database view, and then build a Spec
against the view.

**Comment by adamw** [comment] 2024-08-07 08:12
Hm well views seem to be quite a "heavyweight" solution, as that's a database object that you have to first create. So simply "writing a query and getting results" becomes much harder. Views are definitely a solution, but I think it would be great if magnum would be less opinionated here and allow for constructing ad-hoc complex queries as well.

**Comment by AugustNagro** [comment] 2024-10-15 06:48
Good point @adamw . Giving this some more thought, I've opened two WIP merge requests:

1. Support Frag parameters in the sql interpolator: https://github.com/AugustNagro/magnum/pull/51

```scala
  test("embed Frag into Frag"):
    def findPersonCnt(filter: Frag)(using DbCon): Int =
      sql"SELECT count(*) FROM person WHERE $filter".query[Int].run().head
    val isAdminFrag = sql"is_admin = true"
    connect(ds()):
      val johnCnt = findPersonCnt(sql"first_name = 'John' AND $isAdminFrag")
      assertEquals(johnCnt, 2)
```

Pros
* Simple implementation
* Very general purpose and covers all statement types

Cons:
* Can be abused making the SQL layer a complicated mess. I've seen before in other slick/doobie projects and it was a main rational for the Spec class.

2. Enhance Spec to support a user-supplied 'prefix' Frag that ends before the WHERE clause. (WIP MR: https://github.com/AugustNagro/magnum/pull/52 )

```scala
  test("spec with prefix"):
    val age = 3
    val frag = Spec[User](sql"SELECT * FROM user")
      .where(sql"age > $age")
      .build
    assertEquals(frag.sqlString, "SELECT * FROM user WHERE (age > ?)")
    assertEquals(frag.params, Vector(age))
```

Pros:
* Allows one to use Specs without database views if joins are required

Cons:
* Still needs some design thought and only covers dynamic queries (which is however the most common case).

Right now I think both would be valuable. LMK your thoughts.

**Comment by adamw** [comment] 2024-10-18 14:28
Yeah I think both proposals are supplementary. Combining SQLs from fragments is kind of a last-resort thing - discouraged, dangerous, but good to have that "ultimate flexibility" when possible. So I think I would like to have that option. But I agree that using `Spec`s  should be the way to go as long as possible - after all, this gives us type safety. Probably documenting such a "gradual degradation path" of safety (Spec - Spec with prefix - Embedding fragments) will still cause some people to misuse the features, but what can you do ... ;)

**Comment by AugustNagro** [comment] 2024-12-02 00:20
Closed by https://github.com/AugustNagro/magnum/pull/73

**Closed by AugustNagro** 2024-12-02 00:20 UTC

**Comment by adamw** [comment] 2024-12-02 19:49
Sounds good, thanks @AugustNagro! Just to make sure - "direct"-style will also still be possible?

**Comment by AugustNagro** [comment] 2024-12-03 00:26
> Just to make sure - "direct"-style will also still be possible?

100%!

**Comment by AugustNagro** [comment] 2024-12-03 00:28
Please feel free to make feature request issues with changes you'd like to
see in v2.

One thing I have in mind is refactoring the package structure.. it's not
ideal to have everything in the magnum package if using wildcard imports.

**Comment by adamw** [comment] 2024-12-03 07:57
@AugustNagro great to know :) I think I posted all of the issues I had so far ... maye the only thing left would be integration with various "error modes", as exemplified in https://github.com/softwaremill/bootzooka/pull/1364 (thanks for the PR!):

```
def transactEither[E, T](f: DbTx ?=> Either[E, T])(using IO): Either[E, T] =
     try com.augustnagro.magnum.transact(transactor)(Right(f.fold(e => throw LeftException(e), identity)))
     catch case e: LeftException[?] => Left(e.asInstanceOf[LeftException[E]].left)
```

this works, but the try-catch is not ideal. Maybe some way of evaluating the transaction's logic into a `Commit`/`Rollback` result would work here?
